name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    outputs:
      created: ${{ steps.release.outputs.release_created }}
    runs-on: ubuntu-latest
    environment:
      name: codeanim-release
    steps:
      - id: app
        uses: actions/create-github-app-token@v2.2.1
        with:
          app-id: 1855004
          private-key: ${{ secrets.RELEASER_PRIVATE_KEY }}
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          token: ${{ steps.app.outputs.token }}
  publish:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.created }}
    environment:
      name: codeanim-release
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv build
      - run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
